[general]
import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]

[font]
normal = { family = "FiraCodeNerdFontMono", style = "Regular" }
size = 14.0

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }
thickness = 0.225

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

